### ISSUE TITLE
Import [Oi]

### ISSUE THREAD

**Issue by tgrandje** [GeorgioWan/Oi#10]
Hello GeorgioWan (and thanks for your great work by the way)
The button "Import your [Oi]" on the [editor](https://oawan.me/Oi/editor/#/overview) doesn't seem to work on my machine (using Firefox as navigator) : nothing happens when it is clicked.
As you crossed it from the todo list on the main page, I thought it may be a bug ?

**Comment by GeorgioWan** [comment]
Hi @tgrandje 

Thanks for your issue, and [I fixed the problem on Firefox](https://github.com/GeorgioWan/Oi/commit/1eecd3233495edfb9d87f1004d1a8216a5b3abc1)

Please give it a try again, thanks a lot!

> Small Tips: remember to clear the cached.

**Comment by tgrandje** [comment]
Great, it works !
Thanks again
