### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by QuadStingray** [GeorgioWan/Oi#8]
Hi, 

the tool looks very great! 

I'm missing two functions, maybe I only didn't see them. :-)

1. First reordering for the slides is only possible by export and import the project?
2. It would be cool, when you could change the position of the slides by drag-and-drop

**Comment by GeorgioWan** [comment]
Hi @QuadStingray 
I'm glad for taking this question and suggestion.

For the first, **[ Oi ]** does'nt support reorder slides currently (but this is necessary!!)
And the DRAG-AND-DROP is roughly finished, but... not work very well when I tested it XP

---

Let me show you something about these (but I'm not really sure when can release... 😭 )

**1. More intuitive editor**
![Oi](http://i.imgur.com/UQrykwA.gif)

**2. Drag-and-Drop to change element of slides**
![Oi](http://i.imgur.com/XRMdNrJ.gif)

**3. Maybe inser image**
![Oi](http://i.imgur.com/wjaJSZB.gif)

---

Thanks again for your issue.

**Comment by QuadStingray** [comment]
👍 That looks great!
